### ISSUE TITLE
Question about figure2 in the paper

### ISSUE THREAD

**Issue by buaacyw** [fudan-zvg/PGC-3D#2]
Thanks for your nice work!
![0b7fa4eb70ace3cfdc90f0482a6fcdc](https://github.com/fudan-zvg/PGC-3D/assets/52091468/3a010868-03c2-4057-8413-c1405bf9e790)

What's the difference between backpropagation of latent gradients and VAE gradients?
In my understanding, the former one means vanilla SDS loss backpropagation. But what's the latter one?

**Comment by mdarhdarz** [comment]
If using SDXL,
latent gradients (size 128x128) <-> optimize 128x128 latents -> decode latents to get RGB image
vae gradients (size 1024x1024) <-> optimize 1024x1024 RGB image (no need to decode)

You can find more details in 2dplayground.ipynb in threestudio.

**Comment by buaacyw** [comment]
Thanks a lot!
